[build]
command = "npm run build"
#command="ntli build -a"
functions=".ntli/site/netlify/functions"
#publish=".ntli/site/static"
publish = ".next"

[[headers]]
for="/ui/*"
[headers.values]
Access-Control-Allow-Origin="*"
Access-Control-Allow-Headers="*"
Access-Control-Allow-Methods="*"

[functions]
node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"



