[build]

     command: npm run build
     commandOrigin: config
     environment:
       - DYNAMIC_CSP_BUILD_TOKEN
       - NEXT_PRIVATE_TARGET
     publish: /opt/build/repo/.next
     publishOrigin: config
   functions:
     '*':
       node_bundler: esbuild
   functionsDirectory: /opt/build/repo/.ntli/site/netlify/functions
   headers:
     - for: /ui/*

[[headers]]
for="/ui/*"
[headers.values]
Access-Control-Allow-Origin="*"
Access-Control-Allow-Headers="*"
Access-Control-Allow-Methods="*"

[functions]
node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"



